apiVersion: v1
kind: Secret
metadata:
  name: signing-secrets
  namespace: tekton-trusted-resources
  labels:
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: tekton-trusted-resources
# The data is populated at install time.
# data:
