kind: TaskRun
apiVersion: tekton.dev/v1beta1
metadata:
  annotations:
      # add signature for verification
      #tekton.dev/signature: MEYCIQDhKiJpPylEFo5RmBEZV96luADJdhSQcE7EZuOgL7hk8wIhAICKk6o5ldqo2sN0R6GhE7GpuEkblbjeJilNms78E+ap
      #tekton.dev/key: kms://
  name: example-tr
  namespace: tekton-trusted-resources
spec:
  taskSpec:
    steps:
      - image: ubuntu
        name: echo
